# Generated by Django 5.1.15 on 2026-04-25 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0023_alter_profile_pronouns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"permissions": [("can_organize", "Can Organize")]},
        ),
    ]
