# Generated by Django 5.1.15 on 2026-07-01 14:56

import cms.models
import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0018_alter_cmsstreampage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsstreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("card", 4),
                    ("paragraph", 6),
                    ("html", 7),
                    ("table", 8),
                    ("newsletter_signup", 9),
                    ("display_card_block", 12),
                    ("collapsible_header", 16),
                    ("content_button_block", 28),
                ],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageBlock", [], {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("image_side", 1), ("header", 2), ("text", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 5), ("paragraph", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    8: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "copy",
                                    "cut",
                                    "---------",
                                    "alignment",
                                ],
                                "editor": "text",
                                "renderer": "html",
                            }
                        },
                    ),
                    9: ("wagtail.blocks.StructBlock", [[]], {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": cms.models.get_collections, "label": "Collection to display"},
                    ),
                    11: ("wagtail.blocks.BooleanBlock", (), {"default": True, "required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("collection", 10), ("card_count_description", 2), ("random_order", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h1", "Header 1"),
                                ("h2", "Header 2"),
                                ("h3", "Header 3"),
                                ("h4", "Header 4"),
                            ]
                        },
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {}),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card", 4),
                                ("paragraph", 6),
                                ("html", 7),
                                ("table", 8),
                                ("display_card_block", 12),
                            ]
                        ],
                        {"use_json_field": True},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title_header", 13), ("title", 14), ("body", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"form_classname": "page_link", "label": "Page", "required": False},
                    ),
                    19: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"form_classname": "file_link", "label": "File", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [
                                wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()
                            ],
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "anchor_link",
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    22: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "phone_link",
                            "label": "Phone",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "form_classname": "new_window_toggle",
                            "label": "Open in new window",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 17),
                                ("page", 18),
                                ("file", 19),
                                ("custom_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("phone", 23),
                                ("new_window", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A FontAwesome icon name, see <a href="https://fontawesome.com/search?ic=free">here</a> for list of options',
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("center", "Center")], "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 14), ("url", 25), ("icon", 26), ("alignment", 27)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="postpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("card", 4),
                    ("paragraph", 6),
                    ("html", 7),
                    ("table", 8),
                    ("newsletter_signup", 9),
                    ("content_button_block", 22),
                ],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageBlock", [], {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("image_side", 1), ("header", 2), ("text", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 5), ("paragraph", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    8: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "copy",
                                    "cut",
                                    "---------",
                                    "alignment",
                                ],
                                "editor": "text",
                                "renderer": "html",
                            }
                        },
                    ),
                    9: ("wagtail.blocks.StructBlock", [[]], {}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"form_classname": "page_link", "label": "Page", "required": False},
                    ),
                    13: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"form_classname": "file_link", "label": "File", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [
                                wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()
                            ],
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "anchor_link",
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "phone_link",
                            "label": "Phone",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "form_classname": "new_window_toggle",
                            "label": "Open in new window",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 11),
                                ("page", 12),
                                ("file", 13),
                                ("custom_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("phone", 17),
                                ("new_window", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A FontAwesome icon name, see <a href="https://fontawesome.com/search?ic=free">here</a> for list of options',
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("center", "Center")], "required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 10), ("url", 19), ("icon", 20), ("alignment", 21)]],
                        {},
                    ),
                },
            ),
        ),
    ]
