# Generated by Django 5.1.15 on 2026-05-09 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBlastTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailBlast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("reply_to", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_blasts",
                        to="emailblasts.emailblasttarget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailBlastTargetNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[("and", "All of these"), ("or", "Any of these")],
                        max_length=8,
                    ),
                ),
                (
                    "primitive_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_profiles", "All profiles"),
                            ("district", "District"),
                            ("rco", "Registered Community Organization"),
                            ("ward", "Ward"),
                            ("division", "Division"),
                            ("geojson", "GeoJSON boundary"),
                            ("petition", "Petition signers"),
                            ("legacy", "Legacy/custom targeting"),
                        ],
                        max_length=32,
                    ),
                ),
                ("primitive_id", models.CharField(blank=True, max_length=64)),
                ("primitive_name", models.CharField(blank=True, max_length=255)),
                ("primitive_geojson", models.JSONField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="emailblasts.emailblasttargetnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="emailblasts.emailblasttarget",
                    ),
                ),
            ],
        ),
    ]
