# Generated by Django 5.1.15 on 2026-05-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailblasts", "0001_initial"),
        ("profiles", "0024_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailblast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="EmailBlastDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_blast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="emailblasts.emailblast",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "email blast deliveries",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email_blast", "email"), name="unique_email_blast_delivery_email"
                    )
                ],
            },
        ),
    ]
