# Generated by Django 5.1.15 on 2026-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailblasts", "0002_alter_emailblast_status_emailblastdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailblasttargetnode",
            name="primitive_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_profiles", "All profiles"),
                    ("district", "District"),
                    ("rco", "Registered Community Organization"),
                    ("ward", "Ward"),
                    ("division", "Division"),
                    ("geojson", "GeoJSON boundary"),
                    ("petition", "Petition signers"),
                    ("event_signin", "Event sign-ins"),
                    ("legacy", "Legacy/custom targeting"),
                ],
                max_length=32,
            ),
        ),
    ]
